definitions:
  entity.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entity.Notify:
    properties:
      frequency:
        type: string
      hour:
        type: integer
      minute:
        type: integer
      weekday:
        type: integer
    type: object
  entity.Package:
    properties:
      file:
        type: string
      isOutdated:
        type: boolean
      name:
        type: string
      version:
        $ref: '#/definitions/entity.PackageVersion'
    type: object
  entity.PackageVersion:
    properties:
      current:
        type: string
      last:
        type: string
    type: object
  entity.RepoDTO:
    properties:
      id:
        type: string
      name:
        type: string
      owner:
        type: string
      packageList:
        items:
          $ref: '#/definitions/entity.Package'
        type: array
      path:
        type: string
      provider:
        type: string
      userID:
        type: string
    type: object
  entity.RepoIDRequest:
    properties:
      id:
        type: string
    type: object
  entity.RepoUrlRequest:
    properties:
      url:
        type: string
    type: object
  entity.Response:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
  entity.SignUp:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  entity.SubscriberDTO:
    properties:
      email:
        type: string
      id:
        type: string
      isConfirmed:
        type: boolean
      notify:
        $ref: '#/definitions/entity.Notify'
      repoID:
        type: string
    type: object
  entity.SubscriberIDRequest:
    properties:
      id:
        type: string
    type: object
  entity.SubscriberRequest:
    properties:
      email:
        type: string
      notify:
        $ref: '#/definitions/entity.Notify'
      repoID:
        type: string
    type: object
  entity.TokenResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  entity.UserDTO:
    properties:
      email:
        type: string
      id:
        type: string
      isConfirmed:
        type: boolean
      name:
        type: string
      password:
        type: string
    type: object
  errors.AppError:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: ozgur@nozgurozturk.com
    name: Ozgur Ozturk
  description: API for Marvin outdated package dependency notification service
  title: Marvin
  version: 0.0.1
paths:
  /api/repository:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RepoIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Remove repository and subscribers belongs to it
      tags:
      - repo
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.RepoDTO'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Returns all git repository that user have
      tags:
      - repo
    post:
      consumes:
      - application/json
      parameters:
      - description: Url
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RepoUrlRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.RepoDTO'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Create new git repository with packages
      tags:
      - repo
    put:
      consumes:
      - application/json
      parameters:
      - description: Id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RepoIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.RepoDTO'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Updates dependencies and compare versions
      tags:
      - repo
  /api/subscriber:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SubscriberIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Remove subscriber from repository
      tags:
      - subscriber
    post:
      consumes:
      - application/json
      parameters:
      - description: Subscriber
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SubscriberRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.SubscriberDTO'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Create subscriber belongs to repository and send email
      tags:
      - subscriber
  /api/subscriber/all:
    post:
      consumes:
      - application/json
      parameters:
      - description: Id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RepoIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.SubscriberDTO'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Returns all subscriber belongs to repository
      tags:
      - subscriber
  /api/subscriber/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: Subscriber
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SubscriberRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.SubscriberDTO'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Send confirm email to existing subscriber
      tags:
      - subscriber
  /api/user:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Removes user
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.UserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.UserDTO'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Updates user values (Accept partial updates)
      tags:
      - user
  /auth/confirm:
    get:
      parameters:
      - description: token
        in: query
        name: t
        required: true
        type: string
      produces:
      - text/html
      summary: Verify user's account
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.TokenResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Login with user credentials
      tags:
      - auth
  /auth/logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Drops user's session
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.TokenResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Renew user's session
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sign up
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.TokenResponse'
              type: object
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Create new user and send verification email
      tags:
      - auth
  /subscriber:
    get:
      parameters:
      - description: token
        in: query
        name: t
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Render subscriber's notification preferences page
      tags:
      - subscriber
  /subscriber/confirm:
    get:
      parameters:
      - description: token
        in: query
        name: t
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Verify subscriber's email
      tags:
      - subscriber
  /subscriber/unsubscribe:
    get:
      parameters:
      - description: token
        in: query
        name: t
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Unsubscribe subscriber's email
      tags:
      - subscriber
  /subscriber/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: Subscriber
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SubscriberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.AppError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Update subscriber's notification preferences
      tags:
      - subscriber
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
